// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbclfeabzxivkucxkgph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiY2xmZWFienhpdmt1Y3hrZ3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzgwNjAsImV4cCI6MjA3MzQxNDA2MH0.q0Wx9KeJFIOcTdlyfYeWbGzzMc4Ijx1r2wphSulWrg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});